export const FETCH_CHAT_HISTORY_REQUEST = "FETCH_CHAT_HISTORY_REQUEST";
export const FETCH_CHAT_HISTORY_SUCCESS = "FETCH_CHAT_HISTORY_SUCCESS";
export const FETCH_CHAT_HISTORY_FAILURE = "FETCH_CHAT_HISTORY_FAILURE";
export const FETCH_CHAT_HISTORY = "FETCH_CHAT_HISTORY";
export const ADD_MESSAGE = 'ADD_MESSAGE';