export const CREATE_USER_STAYCATION_REQUEST = 'CREATE_USER_STAYCATION_REQUEST';
export const CREATE_USER_STAYCATION_SUCCESS = 'CREATE_USER_STAYCATION_SUCCESS';
export const CREATE_USER_STAYCATION_FAILURE = 'CREATE_USER_STAYCATION_FAILURE';

export const FETCH_USER_STAYCATIONS_REQUEST = 'FETCH_USER_STAYCATIONS_REQUEST';
export const FETCH_USER_STAYCATIONS_SUCCESS = 'FETCH_USER_STAYCATIONS_SUCCESS';
export const FETCH_USER_STAYCATIONS_FAILURE = 'FETCH_USER_STAYCATIONS_FAILURE';
